name: Generate Podcast Feed
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.5
      - name: Run Feed Generator
        uses: spiffai/podcast-generator@main
